[build]
  publish = "."
  functions = "netlify/functions"

# Scheduled function to update product prices weekly
[functions."scheduled-price-update"]
  schedule = "0 2 * * 0"  # Every Sunday at 2:00 AM UTC

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200